FilmDB/Controllers/FilmController.cs
using FilmDB.Models;
using FilmDB.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FilmDB.Controllers
{
    public class FilmController : Controller
    {
        private readonly FilmManager _filmManager;
        private readonly GenreManager _genreManager;
        public FilmController(FilmManager filmManager, GenreManager genreManager) 
        { 
            _filmManager = filmManager;
            _genreManager = genreManager;
        }
        public IActionResult Index()
        {
            var films = _filmManager.GetFilms();
            return View(films);
        }

        [HttpGet]
        public IActionResult AddFilm() 
        {
            ViewBag.Genres = new SelectList(_genreManager.GetGenresSync(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult AddFilm(Film film)
        {
            try
            {
                _filmManager.AddFilm(film);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View(film);
            }             
        }

        [HttpGet]
        public IActionResult EditFilm(int id)
        {
            var filmToEdit = _filmManager.GetFilm(id);
            if (filmToEdit != null)
            {
                return View(filmToEdit);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public IActionResult EditFilm(Film film)
        {
            if (film != null)
            {
                _filmManager.UpdateFilm(film);
                return RedirectToAction("Index");   
            }
            else
            {
                return View(film);
            }   
        }

        [HttpGet]
        public ActionResult Details(int id) 
        {
            var film = _filmManager.GetFilm(id);
            if (film != null)
            {
                return View(film);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult RemoveFilm(int id) 
        {
            var filmToDelete = _filmManager.GetFilm(id);
            if (filmToDelete != null)
            {
                return View(filmToDelete);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Remove(int id)
        { 
            var filmToDelete = _filmManager.GetFilm(id);
            if (filmToDelete != null)
            {
                _filmManager.RemoveFilm(id);
                return RedirectToAction("Index");
            }
            else 
            {
                return View("RemoveFilm", id);
            }
        }
    }
}

FilmDB/Controllers/GenresController.cs
using FilmDB.Models;
using FilmDB.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FilmDB.Controllers
{
    public class GenresController : Controller
    {
        private readonly GenreManager _genreManager;

        public GenresController(GenreManager genreManager)
        {
            _genreManager = genreManager;
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
            return View(await _genreManager.GetGenres());
        }

        public IActionResult AddGenre()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddGenre(Genre genre)
        {
            if (ModelState.IsValid)
            {
                await _genreManager.AddGenre(genre); 
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }
    }
}

FilmDB/Controllers/RoleController.cs
using FilmDB.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FilmDB.Controllers
{
    [Authorize]
    public class RoleController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;   
        private UserManager<IdentityUser> _userManager;
        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var roles = _roleManager.Roles;
            var user = await _userManager.GetUserAsync(User);
            var userRoles = await _userManager.GetRolesAsync(user);
            return View(roles);
        }

        [HttpGet]
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(AddRole addRole) 
        {
            var newRole = new IdentityRole(addRole.Name);
            var result = await _roleManager.CreateAsync(newRole);

            if (result.Succeeded)
            { 
                return RedirectToAction("Index");
            }
            else
            {
                return View(addRole);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddUserToRole()
        {
            var roles = _roleManager.Roles;
            var users = _userManager.Users;
            RolesAndUsers rau = new RolesAndUsers() 
            { 
                Roles = roles,
                Users = users
            };
            return View(rau);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddUserRols(string userNamew, List<string> Roles) 
        {
            var user = await _userManager.FindByNameAsync(userNamew);
            foreach (var role in Roles)
            {
                await _userManager.AddToRoleAsync(user, role);
            }

            return Ok();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddUserToRole(List<string> Roles, List<string> Users)
        {
            foreach (var item in Users)
            {
                await AddUserRols(item, Roles);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveRole()
        {
            ViewBag.Roles = _roleManager.Roles;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RemoveRole(string Name)
        {
            var roleToDelete = await _roleManager.FindByNameAsync(Name);

            if (roleToDelete != null)
            {
                var result = await _roleManager.DeleteAsync(roleToDelete);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

    }
}

FilmDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FilmDB</title>
    <environment include="Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    </environment>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/FilmDB.styles.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FilmDB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Film" asp-action="Index">Film</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genres" asp-action="Index">Gatunki</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FilmDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>